### ISSUE TITLE
No such file or directory: 'reconstructed/my_file.txt'

### ISSUE THREAD

**Issue by allansifuna** [Wizock/file_chunker#1]
Am getting this error and going through the code i realized you have no way of knowing if the reconstructed folder exists before you write the reconstructed file to it. You might wanna consider adding a snippet that checks if the folder exists or else create it first or instead of creating a folder entirely you can change ```with open(f"reconstructed/{self.file_name}", "wb+") as reconstructed_file:``` to ```with open(f"reconstructed_{self.file_name}", "wb+") as reconstructed_file:``` .

**Comment by crushr3sist** [comment]
How's it going Mr Allan Sifuna. I just wanna thank you for taking a moment to check out my library and taking time to test it out and alongside, and provide feedback. I appreciate that and you've given me a very good idea to implement a more blendable approach to the library design so anyone who's working with files can mix in this library with their project. 

You should watch the library to catch the new implementation of this library, it's going to be worth it.
